#%RAML 1.0
title: Arrowhead - Blockchain Adapter
version: v1
baseUri: https://api-omni.kickstartteam.es
documentation:
 - title: Summary
   content: !include README.md

mediaType: application/json

types:
  SmartContract: !include schemas/smartContract.json
  Transaction: !include schemas/transaction.json

securitySchemes:
  oauth_2_0: !include ./securitySchemes/oauth_2_0.yml

/smartcontract:
  displayName: Smart Contract Entity
  description: Smart Contract Entity description

  post:
    description: Create a new Smart Contract
    securedBy: [ oauth_2_0 ]
    headers:
    body:
      application/json:
        type: SmartContract
    responses:
      202:

  /{address}:
    uriParameters:
      address:
        type: string

    post:
      description: execute transaction in a Smart Contract
      securedBy: [ oauth_2_0 ]
      headers:
      body:
        application/json:
          type: Transaction
      responses:
        202:
