#%RAML 1.0
title: Arrowhead - Blockchain Adapter
version: v1
baseUri: https://api-archer.kickstartteam.es
documentation:
 - title: Summary
   content: !include README.md

mediaType: application/json

types:
  SmartContract: !include schemas/ethereum/smartContracts/register.json
  TransactionInvokeByParam: !include schemas/ethereum/smartContracts/transactionInvokeByParam.json
  TransactionInvoke: !include schemas/ethereum/smartContracts/transactionInvoke.json
  TransactionDeploy: !include schemas/ethereum/smartContracts/transactionDeploy.json

securitySchemes:
  oauth_2_0: !include ./securitySchemes/oauth_2_0.yml

/{dlt_type}:
  uriParameters:
    dlt_type:
      type: string

  /smartcontracts:
    displayName: Smart Contract  

    post:
      description: Register a deployed Smart Contract
      securedBy: [ oauth_2_0 ]
      headers:
      body:
        application/json:
          type: SmartContract
      responses:
        200:

    /{address|alias}:
      uriParameters:
        address:
          type: string

      post:
        description: adapt transaction in the registered Smart Contract
        securedBy: [ oauth_2_0 ]
        headers:
        body:
          application/json:
            type: TransactionInvokeByParam
        responses:
          200:
      get:
        description: retrieve ABI from registered Smart Contract
        securedBy: [ oauth_2_0 ]
    /deploy:
      post:
        description: adapt a Smart Contract deployment transaction
        securedBy: [ oauth_2_0 ]
        body:
          application/json:
            type: TransactionDeploy
        responses:
          200:
    /invoke:
      post:
        description: adapt a Smart Contract invocation transaction
        securedBy: [ oauth_2_0 ]
        body:
          application/json:
            type: TransactionInvoke
        responses:
          200:
  /transfers:
    post:
      description: transfer dlt native cryptocurrency
  /notarizations:
    post:
      description: write metadata in blockchain
  /balance:
    get:
      description: obtain the native cryptocurrency balance of a dlt address
      queryParameters:
        address:
          type: string
  /incentive:
    /average:
      get:
        description: obtain the current average payed as mining incentive e.g. bitcoin fee or ethereum gas
        
  /receipt:
    get:

